Strings table implemented - but firebase.js zipped is bigger.

diff --git a/tools/run-tests b/tools/run-tests
--- a/tools/run-tests
+++ b/tools/run-tests
@@ -18,6 +18,8 @@ if [[ ! -d "node_modules" ]]; then
     exit 1
 fi
 
-mocha lib/test --ui tdd --require "source-map-support/register" "$@"
+if ! mocha lib/test --ui tdd --require "source-map-support/register" "$@"; then
+    echo "Unit tests failed."
+fi
 
 string-pack-js src/test/data/firebase.js
